[tool.poetry]
name = "robo-loader"
version = "0.1.0"
description = ""
authors = ["Semih Koyuncu"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
loguru = "^0.7.2"
pyglet = "^2.0.18"
virtualenv = "^20.27.1"
pydrive = "^1.3.1"
rich = "^13.9.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
